spring.application.name=cordialle-art

# 1. CONFIGURAÇÃO DAS TELAS (JSP)
# ==========================================

# avisa ao Spring onde estão guardadas as páginas HTML/JSP
spring.mvc.view.prefix=/WEB-INF/pages/
# avisa ao Spring qual é a extensão dos arquivos
spring.mvc.view.suffix=.jsp


# ==========================================
# 2. CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL
# ==========================================

# em vez de ter aquela classe ConectaDBPostgres, o spring gerencia isso aqui
spring.datasource.url=jdbc:postgresql://localhost:5432/CordialleArt
spring.datasource.username=postgres
spring.datasource.password=1124
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update